version: '3'

services:
  web:
    container_name: qr_code_app_web_prod
    build: .
    environment:
      RAILS_ENV: production
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/qr_code_app
      - ./public:/qr_code_app/public
      - ./tmp:/qr_code_app/tmp
      - ./log:/qr_code_app/log
    ports:
      - 3000:3000

  nginx:
    container_name: qr_code_app_nginx_prod
    build: containers/nginx
    volumes:
      - ./public:/qr_code_app/public
      - ./tmp:/qr_code_app/tmp
    ports:
      - 80:80
    depends_